export const FIRST_LOAD_START = "FIRST_LOAD_START";
export const FIRST_LOAD_COMPLETE = "FIRST_LOAD_COMPLETE";
export const FIRST_LOAD_ERROR = "FIRST_LOAD_ERROR";
export const USER_STARS_LOAD_START = "USER_STARS_LOAD_START";
export const USER_STARS_LOAD_COMPLETE = "USER_STARS_LOAD_COMPLETE";
export const USER_STARS_LOAD_ERROR = "USER_STARS_LOAD_ERROR";